# Generated by Django 5.1.5 on 2025-02-17 01:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_date_de_publicatio_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_article_ids', to=settings.AUTH_USER_MODEL, verbose_name='auteurs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_article_ids', to='blog.categorie', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
