# Generated by Django 5.1.5 on 2025-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_de_publicatio',
            field=models.DateField(auto_now_add=True, verbose_name='Date de publication'),
        ),
    ]
